setting:
  print-JoinMessage: true
  print-LeftMessage: true
  print-kickMessage: true

messages:
  first-join: "&d`PLAYER` join the game for the first time"
  join: "&e`PLAYER` joined the game"
  left: "&e`PLAYER` left the game"
  kick: "&f`PLAYER` kicked the game \n&c reason: `REASON`"

motd:
  line1: "&7A Minecraft Server"
  line2: ""

